/**
 * Selection of the one turn a resend may shadow, read from the session log
 * alone. Every refusal is decided here, so no caller can reach the surface
 * replacement through a path that skips the turn-ending rule.
 *
 * @module @deepseek-ai/dsh-session-turn-edit-resend/policy
 */

import type { SurfaceReplacement } from '@deepseek-ai/dsh-agent'
import type { Session, SessionEvent, SessionSeq, TurnEndReason, UserMessage } from '@deepseek-ai/dsh-session'
import type { ResendRefusal } from './types.ts'

/** The one turn a resend may shadow. */
export interface ResendTarget {
  /** The direct human prompt whose content the caller edits. */
  readonly prompt: UserMessage
  /** Seq of the target turn's `turn/start`. */
  readonly turnStartSeq: SessionSeq
  /** Number of the target turn. */
  readonly turn: number
  /** Surface range the resent message takes the place of. */
  readonly replacement: SurfaceReplacement
  /**
   * Names of the tools this turn called, deduplicated in first-call order.
   *
   * The turn remains editable, but a resend asks the model to reach the same
   * conclusion again and the tools it already ran may have changed state
   * outside the harness. A consumer presenting the edit must confirm the
   * repeat before submitting; see {@link ResendEligibility}.
   */
  readonly toolCalls: readonly string[]
}

/** Either the one eligible target or the reason there is none. */
export type ResendSelection =
  | { readonly eligible: true; readonly target: ResendTarget }
  | { readonly eligible: false; readonly refusal: ResendRefusal }

function refuse(refusal: ResendRefusal): ResendSelection {
  return { eligible: false, refusal }
}

/**
 * Whether a turn's ending lets this feature replace it: the loop completed it,
 * or the user cancelled it. An error, a block, an output-token ceiling, a
 * crash-orphaned turn, and a fork-seed boundary are endings the harness cannot
 * reproduce, so their turns stay history.
 * @param reason - the `turn/end` reason that closed the latest turn.
 * @returns whether the turn may be replaced.
 */
function replaceableTurnEnd(reason: TurnEndReason): boolean {
  return reason.kind === 'completed' || reason.kind === 'aborted'
}

/**
 * Read the target turn's surface span.
 *
 * The current surface is the authority: a node an earlier resend shadowed is no
 * longer on it, so a turn whose range was already replaced cannot be selected
 * again and its stale range is never submitted.
 * @param turnStartSeq - seq of the target turn's `turn/start`.
 * @param turnEndSeq - seq of the target turn's `turn/end`.
 * @param surface - the session's current surface node sequences.
 * @returns the turn's surface sequences in order.
 */
function turnSurfaceSpan(
  turnStartSeq: SessionSeq,
  turnEndSeq: SessionSeq,
  surface: readonly SessionSeq[],
): SessionSeq[] {
  return surface.filter(seq => seq > turnStartSeq && seq < turnEndSeq)
}

/**
 * Select the most recent replaceable human turn for editing, or the reason no
 * turn is eligible.
 *
 * The target must be the latest turn and must have ended in a state this
 * feature may replace: the loop completed it, or the user cancelled it. A turn
 * the environment failed, blocked, truncated at its token ceiling, or closed
 * as a crash-orphan or fork seed is never rewritten. A cancelled turn that
 * produced no answer remains replaceable, and its range is the prompt alone.
 * Only a direct human prompt is replaceable; context a plugin injected for
 * that turn is regenerated by the next pre-step instead of being carried over.
 *
 * A turn that recorded tool calls stays eligible, and its tool names are
 * returned in {@link ResendTarget.toolCalls}. Its side effects already
 * happened, and a resend asks the model to repeat the calls, so the consumer
 * presenting the edit must confirm that repeat with the user before submitting.
 * @param session - session whose log and current surface are read.
 * @returns the eligible target, or the refusal that excludes it.
 */
export function selectResendTarget(session: Session): ResendSelection {
  const events = session.snapshotEvents()
  const bySeq = new Map<SessionSeq, SessionEvent>()
  for (const event of events) bySeq.set(event.seq, event)

  let turnEndIndex = -1
  for (let index = events.length - 1; index >= 0; index--) {
    const candidate = events[index]
    if (candidate?.type === 'turn/end') {
      turnEndIndex = index
      break
    }
  }
  if (turnEndIndex < 0) return refuse('no-replaceable-turn')
  const turnEnd = events[turnEndIndex]
  if (turnEnd === undefined || turnEnd.type !== 'turn/end' || !replaceableTurnEnd(turnEnd.data.reason)) {
    return refuse('no-replaceable-turn')
  }
  // A turn that opened later owns the surface now, so the settled turn behind
  // it is history rather than the message the user is looking at.
  if (events.slice(turnEndIndex + 1).some(event => event.type === 'turn/start')) {
    return refuse('not-latest-turn')
  }

  const turn = turnEnd.data.turn
  // A turn that ran tools stays editable: the replacement shadows its tool
  // calls and results in the model-visible surface, and the append-only log
  // keeps them. Repetition is disclosed by `toolCalls`, not refused, because
  // the user owns that decision.
  const toolCalls: string[] = []
  for (const event of events) {
    if (event.type === 'tool/call' && event.data.turn === turn && !toolCalls.includes(event.data.name)) {
      toolCalls.push(event.data.name)
    }
  }
  let turnStartSeq: SessionSeq | undefined
  for (let index = turnEndIndex; index >= 0; index--) {
    const event = events[index]
    if (event?.type === 'turn/start' && event.data.turn === turn) {
      turnStartSeq = event.seq
      break
    }
  }
  if (turnStartSeq === undefined) return refuse('no-replaceable-turn')

  const span = turnSurfaceSpan(turnStartSeq, turnEnd.seq, session.surface.nodes)
  // The turn's span may open with a system/context node the loop reserved before
  // the human prompt. A replacement may not shadow the system head, so the range
  // starts at the direct human prompt and carries every later node of the turn.
  const promptIndex = span.findIndex((seq) => {
    const event = bySeq.get(seq)
    return event?.type === 'user/message' && event.data.source.kind === 'user'
  })
  if (promptIndex < 0) return refuse('no-human-prompt')
  const promptSeq = span[promptIndex]
  if (promptSeq === undefined) return refuse('no-human-prompt')
  const opening = bySeq.get(promptSeq)
  if (opening?.type !== 'user/message') return refuse('no-human-prompt')
  const range = span.slice(promptIndex)
  // An aborted turn may have produced no answer at all; its range is then the
  // prompt alone, and resending it simply asks again. The range is only empty
  // when the prompt itself left the surface, which the lookup above excludes.
  if (promptText(opening.data) === undefined) return refuse('no-editable-text')
  const endSeq = range[range.length - 1]
  if (endSeq === undefined) return refuse('no-human-prompt')

  return {
    eligible: true,
    target: {
      prompt: opening.data,
      turnStartSeq,
      turn,
      replacement: {
        startSeq: promptSeq,
        endSeq,
        sourceEventSeqs: range,
      },
      toolCalls,
    },
  }
}

/**
 * Read the text a composer is seeded with when this prompt is edited.
 *
 * The first text block is the human's own text: `admitPromptContent` keeps the
 * client's part order, so attachment and image blocks follow it, and context a
 * plugin contributes to a turn is a separate message.
 * @param prompt - the original human prompt recorded on the surface.
 * @returns the editable text, or undefined when the prompt carries none.
 */
export function promptText(prompt: UserMessage): string | undefined {
  const block = prompt.content.find(candidate => candidate.type === 'text')
  return block?.type === 'text' ? block.text : undefined
}

/**
 * Build the resent message: the original prompt with its first text block
 * replaced, and every other block carried over unchanged.
 *
 * Attachment and image blocks are the harness's durable references to stored
 * uploads, and any further text block belongs to a plugin that derived it from
 * them. Reusing the original message means neither is parsed, re-admitted, or
 * re-stored: the replacement cites content the session already accepted.
 * @param prompt - the original human prompt recorded on the surface.
 * @param text - the edited text.
 * @returns the original message content with only its first text block changed.
 * @throws when the prompt carries no text block, which {@link selectResendTarget} refuses.
 */
export function editPromptContent(
  prompt: UserMessage,
  text: string,
): UserMessage['content'] {
  const index = prompt.content.findIndex(block => block.type === 'text')
  if (index < 0) throw new Error('the prompt to edit carries no text block')
  return prompt.content.toSpliced(index, 1, { type: 'text', text })
}
